# Generated by Django 5.1 on 2024-11-07 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Device', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('NBonLivraison', models.CharField(max_length=255, null=True)),
                ('capacity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SerialNumber', models.CharField(max_length=255, unique=True)),
                ('HostName', models.CharField(max_length=255)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Model', models.CharField(max_length=255)),
                ('Config', models.CharField(max_length=255)),
                ('DeviceStatus', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], default='IN', max_length=3)),
                ('Capacity', models.IntegerField(default=0)),
                ('Garantie', models.BooleanField(default=False)),
                ('Dotation', models.BooleanField(default=False)),
                ('MiseEnRebute', models.BooleanField(default=False)),
                ('NumeroArrivage', models.BooleanField(default=False)),
                ('Retour', models.BooleanField(default=False)),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolEngine.brands')),
                ('DeviceType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolEngine.devicetype')),
            ],
        ),
        migrations.CreateModel(
            name='StocksPerSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='SchoolEngine.school')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolEngine.stock')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolEngine.school')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
