# Generated by Django 5.1 on 2024-11-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolEngine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='HostName',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
