# Generated by Django 5.1 on 2024-11-07 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolEngine', '0002_alter_stock_hostname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SchoolEngine.school'),
        ),
    ]
