# Generated by Django 5.1 on 2024-11-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolEngine', '0006_alter_user_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='admin', max_length=255),
        ),
    ]
